branches:
  only:
    - master

os: osx
language: swift

xcode_project: OrderedDictionary.xcodeproj

matrix:
  include:
    # macOS 10.13 / Xcode 10.0 / Swift 4.2 / Target: macOS
    - osx_image: xcode10
      xcode_scheme: OrderedDictionary-Mac
      env:
        - XCODE_SDK=macosx
        - XCODE_ACTION="build test"
        - XCODE_DESTINATION="arch=x86_64"
        - XCODE_PLAYGROUND_TARGET="x86_64-apple-macosx10.10"
    # macOS 10.13 / Xcode 10.0 / Swift 4.2 / Target: iOS 
    - osx_image: xcode10
      xcode_scheme: OrderedDictionary-iOS
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6s,OS=10.1"

script:
  - .travis/build.sh
