name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos-11:
    name: macOS 11 (Xcode ${{ matrix.xcode }})
    runs-on: macos-11.0
    strategy:
      matrix:
        # See https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md
        xcode:
          - "12.4"   # Swift 5.3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
  
  macos-10_15:
    name: macOS 10.15 (Xcode ${{ matrix.xcode }})
    runs-on: macos-10.15
    strategy:
      matrix:
        # See https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode
        xcode:
          - "12.3"   # Swift 5.3.2
          - "12.2"   # Swift 5.3.1
          - "11.7"   # Swift 5.2.4
          - "11.3.1" # Swift 5.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
  
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: swift:5.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
